;	    CONTROLADOR DE MOTOR A PASOS UNIPOLAR
; 
; AUTOR: RODRÍGUEZ RAMÍREZ LUIS EDUARDO
;	    
;	    EL OBJETIVO DE ESTE CÓDIGO ES CONTROLAR UN MOTOR A PASOS UNIPOLAR A TRAVÉS
; DEL PUERTO B Y UTILIZANDO UN SWITCH COMO CAMBIO DE DIRECCIÓN, EN ESTE CASO EL SWITCH ES RA7
	    
	    LIST P=16F887
	    INCLUDE <P16F887.INC>

	    __CONFIG    _CONFIG1, _LVP_OFF & _FCMEN_ON & _IESO_OFF & _BOR_OFF & _CPD_OFF & _CP_OFF & _MCLRE_ON & _PWRTE_ON & _WDT_OFF & _INTRC_OSC_NOCLKOUT
	    __CONFIG    _CONFIG2, _WRT_OFF & _BOR21V
	    
;	    INICIALIZACIÓN DEL MICROCONTROLADOR
;	    
;DEFINICIÓN DE ESPACIOS DE MEMORIA, ENTRADAS Y SALIDAS, DESACTIVACIÓN DE ENTRADAS ANALÓGICAS
 
	    ORG		0x00
VA	    EQU		0x20
VB	    EQU		0x21
VC	    EQU		0x22
EV	    EQU		0x23
NB	    EQU		0x24	    
	    BSF		STATUS, RP0
	    BSF		STATUS, RP1
	    CLRF	ANSEL
	    CLRF	ANSELH
	    BSF		STATUS, RP0
	    BCF		STATUS, RP1; BANCO 1
	    MOVLW	0xFF
	    MOVWF	TRISA
	    CLRF	TRISB
	    CLRF	TRISC
	    CLRF	TRISD
	    CLRF	TRISE
	    MOVLW	b'11111000' ;
	    MOVWF	OPTION_REG ;SE DEFINE AL TIMER0 COMO CONTADOR
	    BCF		STATUS, RP0
	    BCF		STATUS, RP1
;
;	    PREPARACIÓN PARA EL GIRO DEL MOTOR
;
	    MOVLW	0x0F
	    MOVWF	EV
	    MOVLW	0x01
	    MOVWF	PORTB
	    CLRF	TMR0
	    
;	    GIRO
;	    
;ESTA PARTE DEL CÓDIGO PRODUCE UN GIRO EN CUALQUIER SENTIDO LEYENDO EL PUERTO C
;Y MOSTRANDO EL GIRO EN EL PUERTO B
	    
	    
	    
DERECHA	    CALL	RETARDO
	    BTFSC	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x08
	    MOVWF	PORTC
	    CALL	RETARDO
	    BTFSC	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x04
	    MOVWF	PORTC
	    CALL	RETARDO
	    BTFSC	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x02
	    MOVWF	PORTC
	    CALL	RETARDO
	    BTFSC	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x01
	    MOVWF	PORTC
	    GOTO	DERECHA	    ;Y SE REGRESA
	    
IZQUIERDA   CALL	RETARDO
	    BTFSS	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x01
	    MOVWF	PORTC
	    CALL	RETARDO
	    BTFSS	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x02
	    MOVWF	PORTC
	    CALL	RETARDO
	    BTFSS	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x04
	    MOVWF	PORTC
	    CALL	RETARDO
	    BTFSS	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x08
	    MOVWF	PORTC
	    GOTO	IZQUIERDA   ;Y SE REGRESA
	    
	    
;	    FUNCIÓN PARA DEFINIR RETARDO
;
;FUNCION QUE AYUDA A RALENTIZAR O ACELERAR EL RETARDO
;
RETARDO	    MOVF	TMR0, W
	    MOVWF	PORTB
	    MOVLW	0x0F	    ;ASIGNA "0F" A W
	    ANDWF	PORTA, W    ;HACE LA OPERACION PORTA & "0F" Y LA GUARDA EN W
	    MOVWF	NB	    ;EL RESULTADO SE ALMACENA EN NB
	    MOVLW	0x0F	    ;SE VUELVE A ASIGNAR "0F" A W
	    SUBWF	NB, W	    ;SE HACE LA OPERACION NB-W Y SE GUARDA EN W
	    BTFSC	STATUS, Z   ;EVALUA SI ES 15, SI NO LO ES ENTONCES SE SALTA UNA INSTRUCCIÓN
	    GOTO	ASIGNA8
	    MOVLW	0x07	    ;SE ASIGNA "07" A W
	    SUBWF	NB, W	    ;SE HACE LA OPERACION NB-W Y SE GUARDA EN W
	    BTFSC	STATUS, Z   ;EVALUA SI ES 7, SI NO LO ES ENTONCES SE SALTA UNA INSTRUCCIÓN
	    GOTO	ASIGNA16
	    MOVLW	0x03	    ;SE ASIGNA "03" A W
	    SUBWF	NB, W	    ;SE HACE LA OPERACION NB-W Y SE GUARDA EN W
	    BTFSC	STATUS, Z   ;EVALUA SI ES 3, SI NO LO ES ENTONCES SE SALTA UNA INSTRUCCIÓN
	    GOTO	ASIGNA32
	    MOVLW	0x01	    ;SE ASIGNA "03" A W
	    SUBWF	NB, W	    ;SE HACE LA OPERACION NB-W Y SE GUARDA EN W
	    BTFSC	STATUS, Z   ;EVALUA SI ES 1, SI NO LO ES ENTONCES SE SALTA UNA INSTRUCCIÓN
	    GOTO	ASIGNA64
	    GOTO	TARDADO    ;PARA EL CASO DE SER 1 O CUALQUIER OTRO CASO NO TOMADO EN CUENTA
	    ;ASIGNACION DE RETARDOS
ASIGNA8	    MOVLW	0x0A
	    MOVWF	VC
	    GOTO	PARTE_C
ASIGNA16    MOVLW	0x10
	    MOVWF	VC
	    GOTO	PARTE_C
ASIGNA32    MOVLW	0x20
	    MOVWF	VC
	    GOTO	PARTE_C
ASIGNA64    MOVLW	0x40
	    MOVWF	VC
	    GOTO	PARTE_C
TARDADO	    MOVLW	0xA0
	    MOVWF	VC
	    GOTO	PARTE_C
;	    FUNCION DE RETARDO
; 
;FUNCION QUE UTILIZA EL TIMER0 COMO TEMPORIZADOR PARA QUE EL PROGRAMA TENGA UN RETARDO
; 
PARTE_C	    MOVLW	0x1A
	    MOVWF	VB
PARTE_B	    MOVLW	0x03
	    MOVWF	VA
PARTE_A	    NOP
	    DECFSZ	VA,F
	    GOTO	PARTE_A
	    DECFSZ	VB,F
	    GOTO	PARTE_B
	    DECFSZ	VC,F
	    GOTO	PARTE_C
	    RETURN
	    
;DERECHA	    CALL	RETARDO
;	    BTFSC	PORTA, 7    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
;	    GOTO	IZQUIERDA
;	    RLF		PORTB, W
;	    MOVWF	PORTB
;	    MOVFW	EV
;	    ANDWF	PORTB, W    ;EVALÚA SI ES CERO
;	    BTFSS	STATUS, Z   ;SI ES CERO, ENTONCES SALTA
;	    GOTO	DERECHA	    ;SI NO ES CERO, SE REPITE
;	    MOVLW	0x01	    ;SE VUELVE A ASIGNAR 1 A W
;	    MOVWF	PORTB	    ;Y LUEGO AL PUERTO B
;	    GOTO	DERECHA	    ;Y SE REGRESA
	    
	    END