;
;	    CONTADOR
;	    
	    
	    LIST P=16F887
	    INCLUDE <P16F887.INC>

	    __CONFIG    _CONFIG1, _LVP_OFF & _FCMEN_ON & _IESO_OFF & _BOR_OFF & _CPD_OFF & _CP_OFF & _MCLRE_ON & _PWRTE_ON & _WDT_OFF & _INTRC_OSC_NOCLKOUT
	    __CONFIG    _CONFIG2, _WRT_OFF & _BOR21V
	    
;	    INICIALIZACIÓN DEL MICROCONTROLADOR
;	    
;DEFINICIÓN DE ESPACIOS DE MEMORIA, ENTRADAS Y SALIDAS, DESACTIVACIÓN DE ENTRADAS ANALÓGICAS
 
	    ORG		0x00
;VA	    EQU		0x20
;VB	    EQU		0x21
;VC	    EQU		0x22
;EV	    EQU		0x23
;NB	    EQU		0x24	    
	    BSF		STATUS, RP0
	    BSF		STATUS, RP1
	    CLRF	ANSEL
	    CLRF	ANSELH
	    BSF		STATUS, RP0
	    BCF		STATUS, RP1; BANCO 1
	    MOVLW	0xFF
	    MOVWF	TRISA
	    CLRF	TRISB
	    CLRF	TRISC
	    CLRF	TRISD
	    CLRF	TRISE
	    MOVLW	b'11111000' ;
	    MOVWF	OPTION_REG ;SE DEFINE AL TIMER0 COMO CONTADOR
	    BCF		STATUS, RP0
	    BCF		STATUS, RP1
	    CLRF	TMR0
CICLO	    MOVF	TMR0, W
	    MOVWF	PORTB
	    GOTO	CICLO
	    END