;	    CONTROLADOR DE MOTOR A PASOS UNIPOLAR
; 
; AUTOR: RODRÍGUEZ RAMÍREZ LUIS EDUARDO
;	    
;	    VELOCIDAD MÁXIMA VC = 0X0A
	    
;	    EL OBJETIVO DE ESTE CÓDIGO ES CONTROLAR UN MOTOR A PASOS UNIPOLAR A TRAVÉS
; DEL PUERTO C Y UTILIZANDO DOS POTENCIOMETROS, UNO PARA CONTROLAR LA VELOCIDAD Y EL OTRO PARA LA DIRECCIÓN
;
	    
	    LIST P=16F887
	    INCLUDE <P16F887.INC>

	    __CONFIG    _CONFIG1, _LVP_OFF & _FCMEN_ON & _IESO_OFF & _BOR_OFF & _CPD_OFF & _CP_OFF & _MCLRE_ON & _PWRTE_ON & _WDT_OFF & _INTRC_OSC_NOCLKOUT
	    __CONFIG    _CONFIG2, _WRT_OFF & _BOR21V
	    
;	    INICIALIZACIÓN DEL MICROCONTROLADOR
;	    
;DEFINICIÓN DE ESPACIOS DE MEMORIA, ENTRADAS Y SALIDAS
 
	    ORG		0x00
VA	    EQU		0x20
VB	    EQU		0x21
VC	    EQU		0x22
;EV	    EQU		0x23
NB	    EQU		0x24
VAN5	    EQU		0x25	; Puertos para
VAN6	    EQU		0x26	; guardar los valores
VAN7	    EQU		0x27	; analógicos
	    ;
	    ; Configuración de puertos de entrada/salida
	    ;	Puerto E como entradas analógicas (5,6,7)
	    ;	Puerto B como salidas digitales
	    ;	Puerto A como entradas digitales
	    ;	Los demás puestos no importan
	    BSF		STATUS, RP0
	    BCF		STATUS, RP1 ;BANCO1
	    MOVLW	0xFF
	    MOVWF	TRISA	;PUERTO A COMO ENTRADA
	    CLRF	TRISB
	    CLRF	TRISC
	    CLRF	TRISD
	    MOVWF	TRISE	;PUERTO E COMO ENTRADA
	    ;
	    ;CONFIGURACIÓN DE FUNCIONAMIENTO DEL CONVERSOR A/D
	    ;NO SE CONFIGURARÁ EL ADCON0 AL PRINCIPIO, SÓLO EL ADCON1
	    ;ADCON0 SE IRÁ CONFIGURANDO EN EL CÓDIGO DEBIDO A QUE SE NECESITA
	    ;CAMBIAR ENTRE LAS ENTRADAS ANALÓGICAS 5,6 Y 7
	    ;
	    ;BCF		STATUS, RP0
	    ;BCF		STATUS, RP1
	    ;MOVLW	B'11010101'
	    ;MOVWF	ADCON0
	    BSF		STATUS, RP0
	    BCF		STATUS, RP1
	    CLRF	ADCON1
	    BCF		STATUS, RP0
	    BCF		STATUS, RP1
;
;	    PREPARACIÓN PARA EL GIRO DEL MOTOR Y EL CONTADOR
;
;	    MOVLW	0x0F
;	    MOVWF	EV
	    CLRF	TMR0
	    
;	    GIRO
;	    
;ESTA PARTE DEL CÓDIGO PRODUCE UN GIRO EN CUALQUIER SENTIDO LEYENDO EL PUERTO C
;Y MOSTRANDO EL GIRO EN EL PUERTO B
	    
	    
	    
DERECHA	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSC	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x08
	    MOVWF	PORTC
	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSC	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x04
	    MOVWF	PORTC
	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSC	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x02
	    MOVWF	PORTC
	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSC	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	IZQUIERDA
	    MOVLW	0x01
	    MOVWF	PORTC
	    GOTO	DERECHA	    ;Y SE REGRESA
	    
IZQUIERDA   CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x01
	    MOVWF	PORTC
	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x02
	    MOVWF	PORTC
	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x04
	    MOVWF	PORTC
	    CALL	RETARDO
	    MOVLW	0x7F; 127
	    SUBWF	VAN6, W; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C    ;EVALUA SI HAY CAMBIO DE DIRECCIÓN
	    GOTO	DERECHA
	    MOVLW	0x08
	    MOVWF	PORTC
	    GOTO	IZQUIERDA   ;Y SE REGRESA
	    
	    
;	    FUNCIÓN PARA DEFINIR RETARDO
;
;FUNCION QUE AYUDA A RALENTIZAR O ACELERAR EL RETARDO
;ADEMÁS DE LEER LAS ENTRADAS ANALÓGICAS
RETARDO	    MOVF	TMR0, W ;CUENTA EVENTOS EXTERNOS
	    MOVWF	PORTB
	    GOTO	ANALOGICO;LEE ENTRADAS ANALOGICAS
ASIGNADO    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN F
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD1
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD2
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD3
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD4
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD5
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD6
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD7
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD8
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD9
	    MOVLW	0x19 ;25
	    SUBWF	VAN5,F; HACE LA OPERACION F-W Y LO GUARDA EN W
	    BTFSS	STATUS, C; SI C = 1 EL VALOR ESTÁ DENTRO DEL RANGO
	    GOTO	VELOCIDAD10
	    GOTO	VELOCIDAD10;
;
;	    ASIGNACION DE RETARDOS
;	    
VELOCIDAD1  MOVLW	0xFF
	    MOVWF	VC
	    GOTO	PARTE_C
VELOCIDAD2  MOVLW	0xEF
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD3  MOVLW	0xDF
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD4  MOVLW	0xCF
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD5  MOVLW	0xAF
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD6  MOVLW	0x9F
	    MOVWF	VC
	    GOTO	PARTE_C
VELOCIDAD7  MOVLW	0x7F
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD8  MOVLW	0x5F
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD9  MOVLW	0x3F
	    MOVWF	VC
	    GOTO	PARTE_C	    
VELOCIDAD10 MOVLW	0x1F
	    MOVWF	VC
	    GOTO	PARTE_C	    

;
;   	    CODIGO PARA SELECCIÓN DE ENTRADAS ANALÓGICAS Y GUARDADO DE SU VALOR
;
ANALOGICO   BCF		STATUS, RP0
	    BCF		STATUS, RP1
	    MOVLW	B'11010101' ; PUERTO AN5
	    MOVWF	ADCON0
	    CALL	LEER_AN
	    MOVWF	VAN5;EL VALOR ANALOGICO EN AN5 LO GUARDA EN VAN5
	    MOVLW	B'11011001' ; PUERTO 6
	    MOVWF	ADCON0
	    CALL	LEER_AN
	    MOVWF	VAN6;EL VALOR ANALOGICO EN AN5 LO GUARDA EN VAN6
	    MOVLW	B'11011101' ; PUERTO AN7
	    MOVWF	ADCON0
	    CALL	LEER_AN
	    MOVWF	VAN7;EL VALOR ANALOGICO EN AN5 LO GUARDA EN VAN5
	    GOTO	ASIGNADO
;	    UNCION DE RETARDO
; 
;FUNCION QUE UTILIZA EL TIMER0 COMO TEMPORIZADOR PARA QUE EL PROGRAMA TENGA UN RETARDO
; 
PARTE_C	    MOVLW	0x1A
	    MOVWF	VB
PARTE_B	    MOVLW	0x03
	    MOVWF	VA
PARTE_A	    NOP
	    DECFSZ	VA,F
	    GOTO	PARTE_A
	    DECFSZ	VB,F
	    GOTO	PARTE_B
	    DECFSZ	VC,F
	    GOTO	PARTE_C
	    RETURN
	    
LEER_AN	    BSF		ADCON0, GO;COMIENZA A LEER EL VALOR ANALÓGICO	    
	    BTFSC	ADCON0, GO
	    GOTO	$-1;REPITE LA ÚLTIMA INSTRUCCIÓN
	    MOVF	ADRESH, W;GUARDA EL CONTENIDO EN W
	    RETURN
	    
	    END