	    LIST P=16F887
	    INCLUDE <P16F887.INC>

	    __CONFIG    _CONFIG1, _LVP_OFF & _FCMEN_ON & _IESO_OFF & _BOR_OFF & _CPD_OFF & _CP_OFF & _MCLRE_ON & _PWRTE_ON & _WDT_OFF & _INTRC_OSC_NOCLKOUT
	    __CONFIG    _CONFIG2, _WRT_OFF & _BOR21V
	    
	    ORG		0x00
VA	    EQU		0x20
VB	    EQU		0x21
VC	    EQU		0x22
	    BSF		STATUS, RP0
	    BSF		STATUS, RP1
	    CLRF	ANSEL
	    CLRF	ANSELH
	    BSF		STATUS, RP0
	    BCF		STATUS, RP1
	    CLRF	TRISA
	    CLRF	TRISB
	    CLRF	TRISC
	    CLRF	TRISD
	    CLRF	TRISE
	    BCF		STATUS, RP0
	    BCF		STATUS, RP1
	    MOVLW	0x00
	    MOVWF	PORTB
CICLO_1	    CALL	RETARDO
	    RLF		PORTB,F
	    BTFSS	PORTB,7
	    GOTO	CICLO_1
CICLO_2	    CALL	RETARDO
	    RRF		PORTB,F
	    BTFSS	PORTB,0
	    GOTO	CICLO_2
	    GOTO	CICLO_1

;ALGORITMO DE RETARDO
	    
RETARDO	    MOVLW	0x01
	    MOVWF	VC
PARTE_C	    MOVLW	0xFA
	    MOVWF	VB
PARTE_B	    MOVLW	0xF9
	    MOVWF	VA
PARTE_A	    NOP
	    DECFSZ	VA,F
	    GOTO	PARTE_A
	    DECFSZ	VB,F
	    GOTO	PARTE_B
	    DECFSZ	VC,F
	    GOTO	PARTE_C
	    RETURN
	    
	    END